site_name: Genome report 

pages:
- Home: 'index.md'
- Quick Start: 
    - 시작 : quick_start/start.md
    - 회원 가입 : quick_start/member_registration.md
    - 예제 파일 받기 : quick_start/example_download.md
    - 파일 업로드 : quick_start/file_upload.md
    - 샘플 등록 : quick_start/sample_register.md
    - 샘플 특성 부여 : quick_start/sample_feature.md
    - 분석 시작 : quick_start/analysis.md
    - 분석 진행상황 확인 : quick_start/project_status.md
    - 분석 결과 보기 : quick_start/report.md
    - 결과 받기 : quick_start/download.md
    - 끝 : quick_start/end.md
- File Manager :
    - GRUploader: GR_File_Manager.md
    - Web File Uploader: Web_File_Uploader.md
- Report :
    - RNA-seq : report/rnaseq_basic.md
    - Files : report/file_and_directory.md
- License : license.md

theme: readthedocs
markdown_extensions:
  - markdown.extensions.admonition
extra_css: [extra.css]

